# Generated by Django 6.0.6 on 2026-06-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shop_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
                ('vehicle_type', models.CharField(choices=[('Bike', 'Bike'), ('Car', 'Car'), ('Truck', 'Truck'), ('EV', 'Electric Vehicle')], max_length=20)),
                ('available', models.BooleanField(default=True)),
                ('inspection_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('battery_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tyre_change_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('engine_repair_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('oil_change_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('brake_repair_charge', models.DecimalField(decimal_places=2, max_digits=8)),
                ('towing_charge_per_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField(default=0)),
            ],
        ),
    ]
