# Generated by Django 6.0.6 on 2026-06-30 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0002_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
