# Generated by Django 6.0.6 on 2026-08-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0004_mechanic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mechanics/'),
        ),
    ]
