# Generated by Django 6.0.6 on 2026-06-28 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=15)),
                ('customer_location', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mechanics.mechanic')),
            ],
        ),
    ]
